### PR TITLE
RV memory leak no longer an issue

### PR DESCRIPTION
**Pull request by nyotis**
arnold_rv can now be completed

### CODE REVIEW

**Comment by chadrik** [comment]
thanks for confirming that it works.  do you happen to know what version of RV is required to avoid the memory leak?

also, would you mind creating a pull request with the changes you made to update the driver for arnold 4.1?

**Comment by nyotis** [comment]
no problem. rv version 4.0.10

i'm still updating your driver so that is arnold 4.1 compatible and will make a pull with the changes once it works. question: in the test.ass file, what does fump corresponds to? do i generate such a file via RV? 

driver_rv
{
name driver_rv
filename "fump"
host "ws-050"
}

**Comment by chadrik** [comment]
IIRC that is just the name of the file it creates within rv.

**Comment by nyotis** [comment]
cheers. plugin is loaded, i need to debug a segmentation fault though

noticed you are using a lot the 'new' operator. it might worth fixing memory leaks by using C++11 std::shared_pointer or rather boost::shared_pointer since compatibility is an issue

**Comment by nyotis** [comment]
hey chad, i'm getting one segmentation fault. 

below is the details of my machine, plus arnold/rv version, complete gdb log, core dump and disassembly at instruction level

http://codepad.org/G7dVqv63

while backtracing, i am not getting any pointers to functions calls, instead ?? symbols

(gdb) bt
#0  0x0000000000000002 in ?? ()
#1  0x00007fffffffd340 in ?? ()
#2  0x00007fffffffd387 in ?? ()
#3  0x0000000000000000 in ?? ()

see also image attached.
snapshot21

i tried to install some debug packages https://access.redhat.com/site/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/intro.debuginfo.html without any success.
the template log message is not very helpful, hard to decipher thoses nested templates

any ideas?

**Comment by nyotis** [comment]
issue with the driver almost fixed. 
code is still buggy, but at least rv and arnold now talk to each other.
i might fix and upload the code if we feel that rv is the preferred solution

**Comment by nyotis** [comment]
https://github.com/gatgui/arnold-rv

**Pull request closed without merging**
